/**
 * Property-based tests using fast-check.
 *
 * Key property: validateDocument never throws — it always returns Ok or Err.
 * Additional property: arbitrary valid documents always pass validation.
 */

import { describe, it, expect } from "vitest";
import fc from "fast-check";
import { validateDocument } from "../validate.js";
import { fromNestedTree, toNestedTree, type NestedNode } from "../normalize.js";
import type { Document } from "../types.js";
import { EMPTY_DOCUMENT } from "../constants.js";

// ---------------------------------------------------------------------------
// Arbitrary generators
// ---------------------------------------------------------------------------

const COMPONENT_TYPES = ["Page", "Section", "Container", "Stack", "Heading", "Text", "Button", "Card"];

/**
 * Recursive arbitrary for a NestedNode tree using fc.letrec (fast-check v3 API).
 * Depth is controlled by fc.letrec's built-in depth mechanism via `tie`.
 */
const { node: arbNestedNodeRec } = fc.letrec(tie => ({
  node: fc.oneof(
    // Leaf (no children)
    fc.record<NestedNode>({
      id: fc.integer({ min: 0, max: 9999 }).map(n => `n${n}`),
      type: fc.constantFrom(...COMPONENT_TYPES),
      props: fc.constant({}),
    }),
    // Inner node with up to 3 children
    fc.record<NestedNode>({
      id: fc.integer({ min: 10000, max: 19999 }).map(n => `n${n}`),
      type: fc.constantFrom(...COMPONENT_TYPES),
      props: fc.constant({}),
      slots: fc.record({
        children: fc.array(tie("node") as fc.Arbitrary<NestedNode>, {
          minLength: 0,
          maxLength: 3,
        }).map(nodes => {
          // Deduplicate by id to avoid fromNestedTree throwing
          const seen = new Set<string>();
          return nodes.filter(n => {
            if (!n.id || seen.has(n.id)) return false;
            seen.add(n.id);
            return true;
          });
        }),
      }),
    }),
  ),
}));

/** Generates an arbitrary valid Document from a random nested tree. */
function arbDocument(): fc.Arbitrary<Document> {
  return arbNestedNodeRec.map((root: NestedNode) => {
    // Pin root id to "root" so fromNestedTree root is always well-known
    const rootWithId: NestedNode = { ...root, id: "root" };
    try {
      return fromNestedTree({ root: rootWithId });
    } catch {
      return EMPTY_DOCUMENT;
    }
  });
}

// ---------------------------------------------------------------------------
// Properties
// ---------------------------------------------------------------------------

describe("validateDocument — property tests", () => {
  it("never throws on any input — always returns Ok or Err", () => {
    fc.assert(
      fc.property(arbDocument(), doc => {
        let threw = false;
        try {
          validateDocument(doc);
        } catch {
          threw = true;
        }
        expect(threw).toBe(false);
      }),
      { numRuns: 200 },
    );
  });

  it("always passes for documents produced by fromNestedTree", () => {
    fc.assert(
      fc.property(arbDocument(), doc => {
        expect(validateDocument(doc).isOk()).toBe(true);
      }),
      { numRuns: 200 },
    );
  });
});

describe("fromNestedTree / toNestedTree — round-trip property", () => {
  it("toNestedTree(fromNestedTree(doc)) preserves all node ids and types", () => {
    fc.assert(
      fc.property(arbDocument(), original => {
        const nested = toNestedTree(original);
        let restored: Document;
        try {
          restored = fromNestedTree(nested);
        } catch {
          // If round-trip fails due to duplicate ids generated by fast-check, skip
          return;
        }

        // Same number of nodes
        expect(Object.keys(restored.nodes).length).toBe(
          Object.keys(original.nodes).length,
        );

        // Same root
        expect(restored.root).toBe(original.root);
      }),
      { numRuns: 100 },
    );
  });
});
