/**
 * context.ts — system prompt builder (stub; T10 fills the real implementation).
 *
 * The system prompt is the single document the agent reads to understand:
 * 1. What the current page looks like (tree summary).
 * 2. Which components are available and what props they accept.
 * 3. How to use the tools.
 *
 * T10 will add: RAG-retrieved examples, theme tokens, breakpoints,
 * compressed conversation history, and token budget management.
 */

import type { Document } from "@pageforge/ir";
import type { Registry } from "@pageforge/registry";
import { renderTreeSummary } from "./tree-summary.js";

/**
 * Build the agent system prompt from the current document + registry.
 *
 * Stub: returns a minimal but functional prompt.
 * T10 replaces this with the full context pipeline.
 */
export function buildContext(doc: Document, registry: Registry): string {
  const tree = renderTreeSummary(doc, { maxDepth: 5, maxNodes: 100 });
  const componentList = Object.entries(registry)
    .map(([type, def]) => `- ${type}: ${def.description} (category: ${def.category})`)
    .join("\n");

  return [
    "You are PageForge, an AI page-building assistant.",
    "You edit a live page document using the provided tools.",
    "Always call queryTree first to understand the current structure before making changes.",
    "Return a brief explanation of what you did after completing changes.",
    "",
    "## Current document tree",
    "```json",
    JSON.stringify(tree, null, 2),
    "```",
    "",
    "## Available components",
    componentList,
    "",
    "## Rules",
    "- Only use component types listed above.",
    "- A node's `id` field is auto-generated by insertNode — do not supply it unless you have a specific reason.",
    "- Props that are not supplied default to the component's defaults.",
    "- Never nest a node inside itself (creates a cycle).",
    "- Use updateProps to change props; do not delete and re-insert unless restructuring.",
  ].join("\n");
}
